src/Northwind.Web/Controllers/Api/CustomersController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Common.Data.Business;
using Core.Common.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Northwind.Models;

namespace Northwind.Web.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/[controller]")]
    public sealed class CustomersController : BaseApiController
    {
        private readonly IEntityBusiness<Customer> _customerBusiness;

        public CustomersController(IEntityBusiness<Customer> customerBusiness,
            ILoggerFactory loggerFactory) : base(loggerFactory)
        {
            _customerBusiness = customerBusiness;
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> FindByStringId(string id)
        {
            return await ExecuteExceptionsHandledAsyncActionResult(async () =>
           {
               var customer = await _customerBusiness.FindEntityByStringId(id);
               return Json(customer);
           });
        }

        [HttpGet]
        [Route("")]
        public IActionResult List(
            int? pageNumber, int? pageSize, string sortCol,
            string sortDir, string searchTerms)
        {
            return ExecuteExceptionsHandledActionResult(() =>
            {
                OperationResult result = _customerBusiness.ListItems(
                  pageNumber, pageSize, sortCol ?? "CustomerId", sortDir, searchTerms);

                var paginationData = new PaginationData
                {
                    OffsetFromZero = (int)result.ObjectsDictionary["offset"],
                    PageNumber = (int)result.ObjectsDictionary["pageIndex"],
                    PageSize = (int)result.ObjectsDictionary["sizeOfPage"],
                    OffsetUpperBound = (int)result.ObjectsDictionary["offsetUpperBound"],
                    TotalNumberOfRecords = (int)result.ObjectsDictionary["totalNumberOfRecords"],
                    TotalNumberOfPages = (int)result.ObjectsDictionary["totalNumberOfPages"],
                    SearchTermsCommaSeparated = result.ObjectsDictionary["searchTerms"].ToString(),
                    SortColumn = result.ObjectsDictionary["sortCol"].ToString(),
                    SortDirection = result.ObjectsDictionary["sortDir"].ToString()
                };
                var list = result.ObjectsDictionary["list"] as IEnumerable<Customer>;
                var toReturn = Json(new { list, paginationData });

                return toReturn;
            });
        }

    }
}

src/Northwind.Web/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using Core.Common.Data.Business;
using Core.Common.Data.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Northwind.Models;
using Northwind.Web.ViewModels;

namespace Northwind.Web.Controllers
{
    public class CustomersController : BaseController
    {
        private readonly IEntityBusiness<Customer> _customerEntityBusiness;
        private readonly ILogger<CustomersController> _logger;
        

        public CustomersController(
             IEntityBusiness<Customer> customerEntityBusiness,
             IHostingEnvironment hostingEnvironment,
             ILoggerFactory loggerFactory,
             ILogger<CustomersController> logger) : base(loggerFactory)
        {
            _customerEntityBusiness = customerEntityBusiness;
            this.hostingEnvironment = hostingEnvironment;
            _logger = logger;
        }

        public IActionResult Index(
            int? pageNumber, int? pageSize, string sortCol,
            string sortDir, string searchTerms)
        {
            _logger.LogInformation("In the Index of the controller!");
            return ExecuteExceptionsHandledActionResult(() =>
            {
                OperationResult result = _customerEntityBusiness.ListItems(
                pageNumber, pageSize, sortCol ?? "CustomerId", sortDir, searchTerms);

                ViewBag.offset = result.ObjectsDictionary["offset"];
                ViewBag.pageIndex = result.ObjectsDictionary["pageIndex"];
                ViewBag.sizeOfPage = result.ObjectsDictionary["sizeOfPage"];
                ViewBag.offsetUpperBound = result.ObjectsDictionary["offsetUpperBound"];
                ViewBag.totalRecords = result.ObjectsDictionary["totalNumberOfRecords"];
                ViewBag.totalNumberOfPages = result.ObjectsDictionary["totalNumberOfPages"];
                ViewBag.searchTerms = result.ObjectsDictionary["searchTerms"];
                ViewBag.sortCol = result.ObjectsDictionary["sortCol"];
                ViewBag.sortDir = result.ObjectsDictionary["sortDir"];

                var model = new CustomerListingViewModel { CustomersList = result.ObjectsDictionary["list"] as IEnumerable<Customer> };

                return View(model);
            });
        }
    }
}

src/Northwind.Web/ViewComponents/ListPagerViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Northwind.Web.ViewComponents
{
    public class ListPagerViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(
            string controllerName,
            string controllerAction,
            int totalNumberOfItems,
            int pageNumber,
            int pageSize,
            int totalNumberOfPages,
            int offset,
            int offsetUpperBound,
            string sortCol,
            string sortDir,
            string searchTerms)
        {
            ViewBag.offset = offset;
            ViewBag.pageNumber = pageNumber;
            ViewBag.pageSize = pageSize;
            ViewBag.offsetUpperBound = offsetUpperBound;
            ViewBag.totalRecords = totalNumberOfItems;
            ViewBag.sortCol = sortCol;
            ViewBag.sorDir = sortDir;
            ViewBag.searchTerms = searchTerms;
            ViewBag.url = $"{Url.Content("~/")}{controllerName}/{controllerAction}";

            return await Task.FromResult(View());
        }
    }
}

src/Northwind.Web/Views/Customers/Index.cshtml
@model Northwind.Web.ViewModels.CustomerListingViewModel

@{
    ViewData["Title"] = "Items";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<a href="/Customers/Add">Add item</a>

@if (TempData["saved"] != null)
{
    <div class="alert alert-success">Record saved successfully</div>
}

@if (TempData["deletedOk"] != null)
{
    <div class="alert alert-success">Record deleted successfully</div>
}



@if (Model == null)
{
    <div>Sorry there was a probleam loading data from the database.</div>
}
else
{
    if (Model.CustomersList.Count() > 0)
    {
        <table class="table">
            <tr>
                <th>Customer Id</th>
                <th>Name</th>
                <th>Company</th>
                <th></th>
            </tr>
            @foreach (var customer in Model.CustomersList)
            {
                <tr>
                    <td>
                        @customer.CustomerId
                    </td>
                    <td>
                        @customer.ContactName
                    </td>
                    <td>
                        @customer.CompanyName
                    </td>
                    <td>
                        <a asp-controller="Customers"
                           asp-action="Edit"
                           asp-route-id="@customer.CustomerId">
                            Edit
                        </a> |
                        <a asp-controller="Custoemrs"
                           asp-action="Delete"
                           asp-route-id="@customer.CustomerId">
                            Delete
                        </a>
                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        <div>Sorry, there is nothing to show!</div>
    }
    <form asp-controller="Customers" asp-action="Index" method="GET">
        <label asp-for="SearchTerms">Search terms (separated by comma)</label>
        <input asp-for="SearchTerms" class="form-control input-group-sm" />


        <label asp-for="SortCol">Sort column</label>
        <select asp-for="SortCol" asp-items="Model.SortColumns" class="form-control input-group-sm"> </select>
        <label asp-for="SortDir">Sort Direction</label>
        <select asp-for="SortDir" asp-items="Model.SortDirections" class="form-control input-group-sm"> </select>

        <input type="submit" value="Search" class="btn btn-sm" />

    </form>
    @await Component.InvokeAsync("ListPager",
         new
         {
             controllerName = "Customers",
             controllerAction = "Index",
             totalNumberOfItems = ViewBag.totalRecords,
             pageNumber = ViewBag.pageIndex,
             pageSize = ViewBag.sizeOfPage,
             totalNumberOfPages = ViewBag.totalNumberOfPages,
             offset = ViewBag.offset,
             offsetUpperBound = ViewBag.offsetUpperBound,
             searchTerms = ViewBag.searchTerms,
             sortCol = ViewBag.sortCol,
             sortDir = ViewBag.sortDir
         });
}


